/**
 * DOTDAY blog post types - generated by hand from schema/blogPost.schema.json
 * (schemaVersion 1.0.0). This is the TS mirror of the frozen data contract.
 *
 * If you change schema/blogPost.schema.json, update this file to match. The
 * validator (scripts/validate-post.mjs) checks the JSON; these types let the
 * renderer + admin tooling stay type-safe against the same shape.
 */

export type Category =
  | "Buying Guides"
  | "Comparisons"
  | "How-To & Installation"
  | "Product Focused"
  | "Landscape Fabric";

export type PostType =
  | "comparison"
  | "how-to"
  | "buying-guide"
  | "product-feature"
  | "use-case"
  | "contractor"
  | "drainage"
  | "explainer";

export type PrimaryProduct = "SHIELD" | "XBAR" | "TERRA" | "MULTIPLE" | "NONE";

export type Status =
  | "planned"
  | "draft"
  | "in-review"
  | "published"
  | "needs-update";

export interface ImageRef {
  ref: string; // images.json key / Drive file ID / /public path key
  alt: string;
  caption?: string;
  /** CSS object-position for cropping, e.g. "center", "top", "60% 40%".
   *  Lets a hero photo keep its subject in frame when the aspect differs. */
  focalPoint?: string;
}

export interface Social {
  excerpt: string;
  hashtags: string[];
  ogImage: ImageRef;
  pinterestImage?: ImageRef;
  shareButtons: Array<"pinterest" | "facebook" | "x" | "copy">;
  ogType?: "article";
  twitterCard?: "summary_large_image";
}

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  canonical: string;
  noindex?: boolean;
  social: Social;
}

export interface Hero {
  badge: string;
  excerpt: string;
  image: ImageRef;
}

export interface QuickAnswer {
  heading?: string;
  items: string[];
}

// --- Body blocks (discriminated union on _type) ---

export interface ProseBlock {
  _type: "prose";
  eyebrow?: string;
  heading?: string; // H2
  body: string; // markdown-lite; [text](url) links; no em/en dashes
}

export interface ImageBlock {
  _type: "image";
  ref: string;
  alt: string;
  caption?: string;
}

export interface ComparisonTableBlock {
  _type: "comparisonTable";
  heading?: string;
  columns: string[];
  featuredColumn?: number;
  rows: string[][];
}

export interface CalloutBlock {
  _type: "proTip" | "warning";
  heading?: string;
  body: string;
}

export interface StepsBlock {
  _type: "steps";
  heading?: string;
  steps: Array<{ title: string; body: string }>;
}

export interface StatStripBlock {
  _type: "statStrip";
  items: Array<{ value: string; label: string }>;
}

export interface TrustStripBlock {
  _type: "trustStrip";
  heading?: string;
  items: string[];
}

export interface CtaBlock {
  _type: "cta";
  variant: "calculator" | "quiz" | "contractor" | "enquiry";
  eyebrow?: string;
  heading: string;
  body?: string;
  cta:
    | "Find Your Fabric"
    | "Use the Fabric Calculator"
    | "View Installation Guide"
    | "Request a Quote"
    | "Talk to Us"
    | "Request Bulk Pricing"
    | "Shop DOTDAY Products";
  href: string;
}

export type Block =
  | ProseBlock
  | ImageBlock
  | ComparisonTableBlock
  | CalloutBlock
  | StepsBlock
  | StatStripBlock
  | TrustStripBlock
  | CtaBlock;

export interface Faq {
  heading?: string;
  items: Array<{ q: string; a: string }>;
}

export interface RelatedPost {
  title: string;
  url: string;
  category: Category;
}

export interface InternalLink {
  label: string;
  url: string;
}

export interface BlogPost {
  schemaVersion: "1.0.0";
  slug: string;
  title: string;
  category: Category;
  postType?: PostType;
  primaryProduct?: PrimaryProduct;
  focusKeyword: string;
  status: Status;
  migrated?: boolean;
  author: string;
  authorRef?: string;
  publishedAt: string;
  dateModified?: string;
  readTimeMinutes?: number;
  wordCount?: number;
  seo: Seo;
  hero: Hero;
  quickAnswer?: QuickAnswer;
  blocks: Block[];
  faq: Faq;
  closingHashtags?: string[];
  relatedPosts: RelatedPost[];
  internalLinks: InternalLink[];
  images?: Record<string, string>;
  audit?: Record<string, unknown>;
}
